### ISSUE TITLE
[Feature] UI 프로토타입 제작

### ISSUE THREAD

**Issue by syjeuion** [DEPthes/2nd-MVP-BeginVegan-Android#7]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [X] Feature (기능을 개발해보겠습니다!)

## 내용

- UI 프로토타입 제작하기

## 체크리스트

- [x] 기본 구조 구축하기
- [x] UI 관련 디테일 작업하기

**Comment by CHOI97** [comment]
고생하셨습니다.
